require("lucas.plugins-setup")
require("lucas.core.options")
require("lucas.core.keymaps")
require("lucas.core.colorscheme")
require("lucas.plugins.comment")
require("lucas.plugins.nvim-tree")
require("lucas.plugins.lualine")
require("lucas.plugins.telescope")
require("lucas.plugins.nvim-cmp")
require("lucas.plugins.lsp.mason")
require("lucas.plugins.lsp.lspsaga")
require("lucas.plugins.lsp.lspconfig")
require("lucas.plugins.lsp.null-ls")
require("lucas.plugins.autopairs")
-- require("lucas.plugins.treesitter")
require("lucas.plugins.gitsigns")

-- I always hit ":W" instead of ":w" because I linger on the shift key...
vim.cmd("command! Q q")
vim.cmd("command! W w")
vim.cmd("command! Wq wq")
vim.cmd("command! WQ wq")

